### ISSUE TITLE
The "parent" component for the "ar-frame" entity does not recognize uppercase Vuforia database names.

### ISSUE THREAD

**Issue by jennifer-ma** [argonjs/argon-aframe#3]
Code from the vuforia example:

```
<!-- attach to target. x/y in the plane, z up -->
<ar-frame id="frame" trackvisibility="true" visible="false" parent="vuforia.ar.cover" position="0 0 0" rotation="0 0 0">

```

We named our vuforia database AR but had an error when we set "parent="vuforia.AR.cover"", but "parent="vuforia.ar.cover"" works.

**Comment by blairmacintyre** [comment]
This is an aframe/DOM limit. Attribute names are lower case.
