### ISSUE TITLE
Incorrect Link for Cesium In readme.md

### ISSUE THREAD

**Issue by skilfullycurled** [argonjs/argon-aframe#5]
Hi!

The link to Cesium on the section regarding reference should be cesiumjs.org, not cesium.org.

Location: https://github.com/argonjs/argon-aframe/blame/master/README.md#L125

Currently: 

```
Reference frames are specified using [Cesium Entities](http://cesium.org), with the...
```

Should be: 

```
Reference frames are specified using [Cesium Entities](http://cesiumjs.org), with the...
```

**Comment by blairmacintyre** [comment]
Thanks.  fixed.
